Added Log4J for internal CT instance
ExpediaGroup/apiary-replication pull request #8
Opened 2020-03-30 16:02 UTC by abhimanyugupta07

2020-03-30 16:23 UTC, massdosage requested changes

2020-03-30 16:23 UTC, massdosage commented on CHANGELOG.md
> +## [1.2.2] - TBD
Similar to other PR, let's go with 1.3.0

2020-03-30 16:23 UTC, massdosage commented on CHANGELOG.md
> +- Log4j Xml for internal Circus Train instance.
```suggestion
- Log4j XML for internal Circus Train instance.
```

2020-03-30 16:23 UTC, massdosage commented on README.md
> +| ct\_log4j\_xml | Log4j Xml file to be passed to internal Circus Train instance to control log level. | string | n/a | yes |
```suggestion
| ct\_log4j\_xml | Log4j XML file to be passed to internal Circus Train instance to configure logging. | string | n/a | yes |
```

2020-03-30 16:23 UTC, massdosage commented on variables.tf
> +  description = "Log4j Xml file to be passed to internal Circus Train instance to control log level."
```suggestion
  description = "Log4j XML file to be passed to internal Circus Train instance to configure logging."
```

2020-03-31 09:25 UTC, max-jacobs approved these changes

2020-03-31 15:12 UTC, massdosage approved these changes

2020-03-31 15:27 UTC, merged